from datetime import datetime
from typing import Optional
from pydantic import BaseModel, EmailStr, Field

# User Schemas
class UserBase(BaseModel):
    email: EmailStr
    full_name: Optional[str] = None
    role: Optional[str] = "User"

class UserCreate(UserBase):
    password: str = Field(..., min_length=6)

class UserOut(UserBase):
    id: int
    created_at: datetime

    class Config:
        from_attributes = True

# Token Schemas
class Token(BaseModel):
    access_token: str
    token_type: str

class TokenPayload(BaseModel):
    sub: Optional[str] = None
    exp: Optional[int] = None

# Request Schemas for APIs
class ChatRequest(BaseModel):
    message: str = Field(..., description="The query message text sent to the chatbot", examples=["What products do you have?"])

class ReviewRequest(BaseModel):
    review: str = Field(..., description="The customer review text to be evaluated for sentiment", examples=["Excellent quality and great fit!"])

# Response Schemas for APIs
class ProductPredictionResult(BaseModel):
    category: str = Field(..., description="Predicted category class name from the model", examples=["T-shirt"])
    confidence: float = Field(..., description="Prediction confidence score percentage", examples=[95.40])

class FaceRecognitionResult(BaseModel):
    person_id: int = Field(..., description="Identified person classification ID", examples=[23])
    confidence: Optional[float] = Field(None, description="Recognition confidence score percentage", examples=[85.60])

class SentimentAnalysisResult(BaseModel):
    review: str = Field(..., description="The original review text analyzed", examples=["Excellent quality and great fit!"])
    sentiment: str = Field(..., description="Predicted sentiment class (Positive or Negative)", examples=["Positive"])

class ChatbotResponseResult(BaseModel):
    response: str = Field(..., description="Predefined text reply generated by the chatbot system", examples=["Hello! Welcome to SmartRetailAI."])
